# Generated by Django 4.2 on 2023-04-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_url',
        ),
        migrations.DeleteModel(
            name='ArticleURL',
        ),
    ]
